spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      group-id: mastodon-post-events
      properties:
        spring:
          json:
            trusted:
              packages: "org.example.post.gateway.models, org.example.post.gateway.handler"
    topic:
      mastodon-name: mastodon-post-events-topic
logging:
  level:
    org.springframework.kafka: DEBUG